server:
  port: 9090
  forward-headers-strategy: framework
  error:
    include-exception: false
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

api-docs:
  description: Documentation Organization API
  license-url: http://springdoc.org
  title: Organization API
  version: 1.0
  terms-of-service-url: http://swagger.io/terms/
  license: Apache 2.0

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:employee
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tagsSorter: alpha

