global:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  imagePullSecrets: []

api:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: 50
    targetMemory: 50
  replicaCount: 1
  containerPorts:
    http: 9090
  image:
    repository: suayb/spring-native-example
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    clusterIP:
    loadBalancerIP:
  environment:
  ingress:
    enabled: true
    certManager: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: /
    hostName: susimsek.github.io
    tls: []
  resources:
    limits:
      cpu: 256m
      memory: 512Mi
    requests:
      cpu: 128m
      memory: 256Mi
  livenessProbe:
    enabled: fakl
    httpGet:
      path: /actuator/health/liveness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    httpGet:
      path: /actuator/health/readiness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 5
    failureThreshold: 6
    successThreshold: 1
  customLivenessProbe: { }
  customReadinessProbe: { }
  extraVolumeMounts: []
  extraVolumes: []