//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.24 at 08:39:42 PM TRT 
//


package io.github.susimsek.springnativeexample.model;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Entity
@Table(name = "organization")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Getter
@Setter
public class Organization {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "organization_id_seq")
    @SequenceGenerator(name="organization_id_seq", sequenceName = "ORGANIZATION_ID_SEQ", allocationSize = 1)
    private long id;

    @NotBlank
    private String name;
}
